package org.example.structures

data class LanguageData(
    var server: String = "",
    var database: String = "",
    var var_commands: String = "",
    var var_guilds: String = "",
    var var_members: String = "",
    var var_none: String = "",
    var var_perm: String = "",
    var var_aliases: String = "",
    var var_unknown: String = "",
    var bot_info_embed_title: String = "",
    var help_embed_title: String = "",
    var leave_okay_message: String = "",
    var pause_unpaused: String = "",
    var pause_paused: String = "",
    var ping_latency: String = "",
    var play_added_to_queue: String = "",
    var play_playing_now: String = "",
    var no_songs_found: String = "",
    var play_error_loading: String = "",
    var queue_empty: String = "",
    var next_song: String = "",
    var queue_empty2: String = "",
    var stop_message: String = "",
    var connect_need_vc: String = "",
    var connect_connected: String = "",
)
